import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";
import Button from "../components/Button";
import Card from "../components/Card";
import styles from "../styles/Home.module.css";

const YEAR = [
  2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
  2019, 2020,
];

export default function Home() {
  const [data, setData] = useState([]);

  async function programs() {
    const response = await fetch(
      "https://api.spacexdata.com/v3/launches?limit=100"
    );
    const data = await response.json();
    setData(data);
  }

  useEffect(() => {
    programs();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>SpaceX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1>SpaceX Launch Programs</h1>
      </header>

      <aside className={styles.aside}>
        <h3>Filters</h3>
        <div
          style={{
            borderBottom: "1px solid",
            padding: "5px",
            marginBottom: "10px",
          }}
        >
          Launch Year
        </div>
        <div className={styles.buttons}>
          {YEAR.map((year) => (
            <Button key={year} value={year} />
          ))}
        </div>
        <div
          style={{
            borderBottom: "1px solid",
            padding: "5px",
            marginBottom: "10px",
          }}
        >
          Successful Launch
        </div>
        <div className={styles.buttons}>
          <Button value="True" />
          <Button value="False" />
        </div>
        <div
          style={{
            borderBottom: "1px solid",
            padding: "5px",
            marginBottom: "10px",
          }}
        >
          Successful Landing
        </div>
        <div className={styles.buttons}>
          <Button value="True" />
          <Button value="False" />
        </div>
      </aside>

      {/* <div className={styles.card_container}> */}
      <div className={styles.cards}>
        {data.map((data) => (
          <Card data={data} key={data.flight_number} />
        ))}
      </div>
      {/* </div> */}

      <footer className={styles.footer}>
        <a href="" target="_blank" rel="noopener noreferrer">
          Developed by&nbsp; <b> Shrinivas Biradar</b>
        </a>
      </footer>
    </div>
  );
}
