import Head from "next/head";
import Image from "next/image";
import { getData } from "./api";
import { useState, useEffect } from "react";
import Card from "../components/Card";
import Filters from "../components/Filters";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

export default function Home(props) {
  const router = useRouter();
  const [dataO, setDataO] = useState([]);
  const [filteredData, setFilteredData] = useState([]);

  useEffect(() => {
    setFilteredData(props.jsonData);
    setDataO(props.jsonData);
    router.push("/", "/launches?limit=100", { shallow: true });
  }, []);

  async function filterYear(value, launch, land) {
    const response = await fetch(
      `https://api.spacexdata.com/v3/launches?limit=100&launch_success=${launch}&land_success=${land}&launch_year=${value}`
    );
    const data = await response.json();
    // (filteredData) => filteredData.concat(data)
    setFilteredData(data);
    router.push(
      "/",
      `launches?limit=100&launch_success=${launch}&land_success=${land}&launch_year=${value}`,
      { shallow: true }
    );
  }

  async function filterLanding(land) {
    const response = await fetch(
      `https://api.spacexdata.com/v3/launches?limit=100&launch_success=true&land_success=${land}`
    );
    const data = await response.json();
    setFilteredData(data);
    router.push(
      "/",
      `launches?limit=100&launch_success=true&land_success=${land}`,
      { shallow: true }
    );
  }

  async function filterLaunch(launch) {
    const response = await fetch(
      `https://api.spacexdata.com/v3/launches?limit=100&launch_success=${launch}`
    );
    const data = await response.json();
    setFilteredData(data);
    router.push("/", `launches?limit=100&launch_success=${launch}`, {
      shallow: true,
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>SpaceX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1>SpaceX Launch Programs</h1>
      </header>

      <aside className={styles.aside}>
        <Filters
          data={dataO}
          onFilterYear={filterYear}
          onFilterLanding={filterLanding}
          onFilterLaunch={filterLaunch}
        />
      </aside>

      <div className={styles.cards}>
        {filteredData.map((data) => (
          <Card data={data} key={data.flight_number} />
        ))}
      </div>

      <footer className={styles.footer}>
        <a href="" target="_blank" rel="noopener noreferrer">
          Developed by&nbsp; <b> Shrinivas Biradar</b>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const jsonData = await getData();

  return { props: { jsonData } };
}
