import Head from "next/head";
import { getData } from "./api";
import { useState, useEffect } from "react";
import Card from "../components/Card";
import Filters from "../components/Filters";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

export default function Home({ jsonData }) {
  const router = useRouter();
  const [filteredData, setFilteredData] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    setFilteredData(jsonData);
    setIsLoading(false);
  }, [jsonData]);

  async function filterYear(value, launch, land) {
    const response = await fetch(
      `https://api.spacexdata.com/v3/launches?limit=100&launch_success=${launch}&land_success=${land}&launch_year=${value}`
    );
    const data = await response.json();
    // (filteredData) => filteredData.concat(data)
    setFilteredData(data);
    router.push(
      "/",
      `launches?limit=100&launch_success=${launch}&land_success=${land}&launch_year=${value}`,
      { shallow: true }
    );
  }

  async function filterLanding(land) {
    const response = await fetch(
      `https://api.spacexdata.com/v3/launches?limit=100&launch_success=true&land_success=${land}`
    );
    const data = await response.json();
    setFilteredData(data);
    router.push(
      "/",
      `launches?limit=100&launch_success=true&land_success=${land}`,
      { shallow: true }
    );
  }

  async function filterLaunch(launch) {
    const response = await fetch(
      `https://api.spacexdata.com/v3/launches?limit=100&launch_success=${launch}`
    );
    const data = await response.json();
    setFilteredData(data);
    router.push("/", `launches?limit=100&launch_success=${launch}`, {
      shallow: true,
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>SpaceX</title>
        <meta charset="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/logo.png"></link>
      </Head>

      <header className={styles.header}>
        <h1>SpaceX Launch Programs</h1>
      </header>

      <aside className={styles.aside}>
        <Filters
          data={jsonData}
          onFilterYear={filterYear}
          onFilterLanding={filterLanding}
          onFilterLaunch={filterLaunch}
        />
      </aside>

      <div className={styles.cards}>
        {filteredData.length == 0
          ? "No Successful Launch and Land found."
          : !isLoading
          ? filteredData.map((data) => (
              <Card data={data} key={data.flight_number} />
            ))
          : "Loading... Please Wait"}
        {/* {!isLoading
          ? filteredData.map((data) => (
              <Card data={data} key={data.flight_number} />
            ))
          : "Loading... Please Wait"} */}
      </div>

      <footer className={styles.footer}>
        <a
          href="https://shrinivas-portfolio-462.netlify.app/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Developed by&nbsp; <b> Shrinivas Biradar</b>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const jsonData = await getData();

  return { props: { jsonData } };
}
